import './globals.css'
import { LayoutProvider } from '@/utils/contexts/layout'

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ModalProvider } from '@/utils/contexts/modal'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ModalProvider>
          <LayoutProvider>
            {children}
          </LayoutProvider>
        </ModalProvider>
        <div id="modal-root"></div>
      </body>
    </html>
  )
}
